In [1]:
ls

'Rice Genome Project.ipynb'
 RICE_RP.tar.gz
'snp3kvars-CHR1-1-10000-841820070974764979(AusChr10allsnps1-10000).csv'
 snp3kvars-LOC_OS11G01010-168161704215689027.csv
 Untitled.ipynb

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("snp3kvars-LOC_OS11G01010-168161704215689027.csv")

In [4]:
df2 = pd.read_csv("snp3kvars-CHR1-1-10000-841820070974764979(AusChr10allsnps1-10000).csv")

In [5]:
df2

,JAPONICA NIPPONBARE POSITIONS,ASSAY ID,ACCESSION,SUBPOPULATION,MISMATCH,1026,1033,1038,1045,1047,...,9596,9606,9611,9629,9642,9661,9671,9771,9855,9906
0,JAPONICA NIPPONBARE ALLELES,NaN,NaN,NaN,NaN,A,A,A,A,A,...,C,G,A,T,T,C,A,C,T,A
1,MSU7 EFFECTS (cds-Non-synonymous/cds-Synonymou...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,synonymous_variant,synonymous_variant,synonymous_variant,gene_variant,gene_variant,gene_variant,gene_variant,gene_variant,gene_variant,gene_variant
2,UPRH 33::IRGC 61505-1::[IRIS 313-11617],IRIS 313-11617,IRGC 128495,aus,72.0,NaN,NaN,NaN,NaN,NaN,...,C,G,A,T,T,C,G,T,T,A
3,ARC 12920::IRGC 22450-1::[IRIS 313-10892],IRIS 313-10892,IRGC 127149,aus,62.5,NaN,NaN,NaN,NaN,NaN,...,C,G,A,T,T,C,G,C,C,A
4,ARC 11276::IRGC 21278-1::[IRIS 313-10861],IRIS 313-10861,IRGC 127134,aus,62.0,NaN,NaN,NaN,NaN,NaN,...,C,G,A,T,T,C,G,C,T,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,DHAN 263::IRGC 27926-2::[IRIS 313-11025],IRIS 313-11025,IRGC 128030,aus,1.0,A,A,A,A,A,...,C,G,A,T,T,C,A,C,T,A
199,BORO 394::IRGC 29297-2::[IRIS 313-11065],IRIS 313-11065,IRGC 132326,aus,1.0,NaN,NaN,A,NaN,A,...,C,G,A,T,T,C,A,C,T,A
200,KALIBORO 600::IRGC 29367-1::[IRIS 313-11067],IRIS 313-11067,IRGC 127481,aus,1.0,A,A,A,A,A,...,C,G,A,T,T,C,A,C,T,A
201,ARC 11822::IRGC 21677-1::[IRIS 313-10873],IRIS 313-10873,IRGC 127140,aus,0.0,NaN,NaN,NaN,NaN,NaN,...,C,G,A,T,T,C,A,C,T,A
202,BENA JHUPI::IRGC 34850-2::[IRIS 313-11165],IRIS 313-11165,IRGC 127993,aus,0.0,A,A,A,A,A,...,C,G,A,T,T,C,A,C,T,A